"""initial database setup

Revision ID: 7b84a1443d35
Revises:
Create Date: 2024-09-27 14:27:41.422589

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7b84a1443d35"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
