"""initial database setup

Revision ID: e943d8cd49e5
Revises:
Create Date: 2024-09-27 15:02:09.158331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e943d8cd49e5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiment",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("start_on", sa.Date(), nullable=False),
        sa.Column("end_on", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiment_id"), "experiment", ["id"], unique=False)
    op.create_index(op.f("ix_experiment_name"), "experiment", ["name"], unique=False)
    op.create_table(
        "sample_flight",
        sa.Column(
            "correct_sample", sa.Enum("A", "B", "C", name="samplenames"), nullable=False
        ),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sample_flight_id"), "sample_flight", ["id"], unique=False)
    op.create_table(
        "observation",
        sa.Column(
            "experience_level",
            sa.Enum(
                "NON_BEER_DRINKER",
                "GENERAL_BEER_DRINKER",
                "CRAFT_BEER_ENTHUSIAST",
                "HOMEBREWER",
                "BJCP_TRAINING",
                "BJCP_RECOGNIZED_OR_HIGHER",
                name="experiencelevels",
            ),
            nullable=False,
        ),
        sa.Column(
            "chosen_sample", sa.Enum("A", "B", "C", name="samplenames"), nullable=False
        ),
        sa.Column("responded_at", sa.DateTime(), nullable=False),
        sa.Column("sample_flight_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sample_flight_id"],
            ["sample_flight.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_observation_id"), "observation", ["id"], unique=False)
    op.create_table(
        "sample_flight_token",
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("expiry_date", sa.DateTime(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("sample_flight_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_flight_id"],
            ["sample_flight.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sample_flight_token_id"), "sample_flight_token", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sample_flight_token_token"),
        "sample_flight_token",
        ["token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sample_flight_token_token"), table_name="sample_flight_token"
    )
    op.drop_index(op.f("ix_sample_flight_token_id"), table_name="sample_flight_token")
    op.drop_table("sample_flight_token")
    op.drop_index(op.f("ix_observation_id"), table_name="observation")
    op.drop_table("observation")
    op.drop_index(op.f("ix_sample_flight_id"), table_name="sample_flight")
    op.drop_table("sample_flight")
    op.drop_index(op.f("ix_experiment_name"), table_name="experiment")
    op.drop_index(op.f("ix_experiment_id"), table_name="experiment")
    op.drop_table("experiment")
    # ### end Alembic commands ###
